name: LyttleNametag
description: Modern multi-line nametags for TownyReborn
version: ${version}
main: com.lyttledev.lyttlenametag.LyttleNametag
api-version: '26.2'
authors:
  - LyttleDevelopment
  - ThatsATim
  - Stualyttle
  - HZcgc

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
